version: "3.3"
services:
  analyzer:
    image: rutenkolk/jat_analyzer:0.1
    user: root
    ports:
        - "8079:8079"
        - "7687:7687"
        - "7474:7474"
        - "7575:7575"
    volumes:
       - ./jat_data:/tmp/jat
  controller:
    image: rutenkolk/jat_controller:0.2
    ports:
        - "8081:8081"
    volumes:
       - ./jat_data:/tmp/jat
  frontend:
    image: rutenkolk/jat_frontend:0.2
    ports:
        - "8082:8082"
  glue:
    image: rutenkolk/jat_glue:0.1
    ports:
        - "8080:8080"
  refactor:
    image: rutenkolk/jat_refactor:0.2
    user: root
    ports:
        - "8078:8078"
    volumes:
       - ./jat_data:/tmp/jat
